export default [
  { path: "module-ol_array.html", name: "ol​/array", children: [] },
  {
    path: "module-ol_AssertionError-AssertionError.html",
    name: "ol​/AssertionError",
    children: [],
  },
  {
    path: "module-ol_Collection-Collection.html",
    name: "ol​/Collection",
    children: [],
  },
  {
    path: "module-ol_Collection.CollectionEvent.html",
    name: "ol​/Collection​.CollectionEvent",
    children: [],
  },
  { path: "module-ol_color.html", name: "ol​/color", children: [] },
  { path: "module-ol_colorlike.html", name: "ol​/colorlike", children: [] },
  { path: "module-ol_control.html", name: "ol​/control", children: [] },
  {
    path: "module-ol_control_Attribution-Attribution.html",
    name: "ol​/control​/Attribution",
    children: [],
  },
  {
    path: "module-ol_control_Control-Control.html",
    name: "ol​/control​/Control",
    children: [],
  },
  {
    path: "module-ol_control_FullScreen-FullScreen.html",
    name: "ol​/control​/FullScreen",
    children: [],
  },
  {
    path: "module-ol_control_MousePosition-MousePosition.html",
    name: "ol​/control​/MousePosition",
    children: [],
  },
  {
    path: "module-ol_control_OverviewMap-OverviewMap.html",
    name: "ol​/control​/OverviewMap",
    children: [],
  },
  {
    path: "module-ol_control_Rotate-Rotate.html",
    name: "ol​/control​/Rotate",
    children: [],
  },
  {
    path: "module-ol_control_ScaleLine-ScaleLine.html",
    name: "ol​/control​/ScaleLine",
    children: [],
  },
  {
    path: "module-ol_control_ScaleLine.html",
    name: "ol​/control​/ScaleLine",
    children: [],
  },
  {
    path: "module-ol_control_Zoom-Zoom.html",
    name: "ol​/control​/Zoom",
    children: [],
  },
  {
    path: "module-ol_control_ZoomSlider-ZoomSlider.html",
    name: "ol​/control​/ZoomSlider",
    children: [],
  },
  {
    path: "module-ol_control_ZoomToExtent-ZoomToExtent.html",
    name: "ol​/control​/ZoomToExtent",
    children: [],
  },
  { path: "module-ol_coordinate.html", name: "ol​/coordinate", children: [] },
  { path: "module-ol_easing.html", name: "ol​/easing", children: [] },
  { path: "module-ol_events.html", name: "ol​/events", children: [] },
  {
    path: "module-ol_events_condition.html",
    name: "ol​/events​/condition",
    children: [],
  },
  {
    path: "module-ol_events_Event-BaseEvent.html",
    name: "ol​/events​/Event",
    children: [],
  },
  {
    path: "module-ol_events_Target-Target.html",
    name: "ol​/events​/Target",
    children: [],
  },
  { path: "module-ol_extent.html", name: "ol​/extent", children: [] },
  { path: "module-ol_Feature-Feature.html", name: "ol​/Feature", children: [] },
  { path: "module-ol_Feature.html", name: "ol​/Feature", children: [] },
  {
    path: "module-ol_featureloader.html",
    name: "ol​/featureloader",
    children: [],
  },
  {
    path: "module-ol_format_EsriJSON-EsriJSON.html",
    name: "ol​/format​/EsriJSON",
    children: [],
  },
  {
    path: "module-ol_format_EsriJSON.html",
    name: "ol​/format​/EsriJSON",
    children: [],
  },
  {
    path: "module-ol_format_Feature-FeatureFormat.html",
    name: "ol​/format​/Feature",
    children: [],
  },
  {
    path: "module-ol_format_Feature.html",
    name: "ol​/format​/Feature",
    children: [],
  },
  {
    path: "module-ol_format_filter.html",
    name: "ol​/format​/filter",
    children: [],
  },
  {
    path: "module-ol_format_filter_Bbox-Bbox.html",
    name: "ol​/format​/filter​/Bbox",
    children: [],
  },
  {
    path: "module-ol_format_filter_Contains-Contains.html",
    name: "ol​/format​/filter​/Contains",
    children: [],
  },
  {
    path: "module-ol_format_filter_During-During.html",
    name: "ol​/format​/filter​/During",
    children: [],
  },
  {
    path: "module-ol_format_filter_EqualTo-EqualTo.html",
    name: "ol​/format​/filter​/EqualTo",
    children: [],
  },
  {
    path: "module-ol_format_filter_GreaterThan-GreaterThan.html",
    name: "ol​/format​/filter​/GreaterThan",
    children: [],
  },
  {
    path:
      "module-ol_format_filter_GreaterThanOrEqualTo-GreaterThanOrEqualTo.html",
    name: "ol​/format​/filter​/GreaterThanOrEqualTo",
    children: [],
  },
  {
    path: "module-ol_format_filter_Intersects-Intersects.html",
    name: "ol​/format​/filter​/Intersects",
    children: [],
  },
  {
    path: "module-ol_format_filter_IsBetween-IsBetween.html",
    name: "ol​/format​/filter​/IsBetween",
    children: [],
  },
  {
    path: "module-ol_format_filter_IsLike-IsLike.html",
    name: "ol​/format​/filter​/IsLike",
    children: [],
  },
  {
    path: "module-ol_format_filter_IsNull-IsNull.html",
    name: "ol​/format​/filter​/IsNull",
    children: [],
  },
  {
    path: "module-ol_format_filter_LessThan-LessThan.html",
    name: "ol​/format​/filter​/LessThan",
    children: [],
  },
  {
    path: "module-ol_format_filter_LessThanOrEqualTo-LessThanOrEqualTo.html",
    name: "ol​/format​/filter​/LessThanOrEqualTo",
    children: [],
  },
  {
    path: "module-ol_format_filter_Not-Not.html",
    name: "ol​/format​/filter​/Not",
    children: [],
  },
  {
    path: "module-ol_format_filter_NotEqualTo-NotEqualTo.html",
    name: "ol​/format​/filter​/NotEqualTo",
    children: [],
  },
  {
    path: "module-ol_format_filter_Or-Or.html",
    name: "ol​/format​/filter​/Or",
    children: [],
  },
  {
    path: "module-ol_format_filter_Within-Within.html",
    name: "ol​/format​/filter​/Within",
    children: [],
  },
  {
    path: "module-ol_format_GeoJSON-GeoJSON.html",
    name: "ol​/format​/GeoJSON",
    children: [],
  },
  {
    path: "module-ol_format_GeoJSON.html",
    name: "ol​/format​/GeoJSON",
    children: [],
  },
  { path: "module-ol_format_GML.html", name: "ol​/format​/GML", children: [] },
  {
    path: "module-ol_format_GML2-GML2.html",
    name: "ol​/format​/GML2",
    children: [],
  },
  {
    path: "module-ol_format_GML3-GML3.html",
    name: "ol​/format​/GML3",
    children: [],
  },
  {
    path: "module-ol_format_GML32-GML32.html",
    name: "ol​/format​/GML32",
    children: [],
  },
  {
    path: "module-ol_format_GPX-GPX.html",
    name: "ol​/format​/GPX",
    children: [],
  },
  { path: "module-ol_format_GPX.html", name: "ol​/format​/GPX", children: [] },
  {
    path: "module-ol_format_IGC-IGC.html",
    name: "ol​/format​/IGC",
    children: [],
  },
  {
    path: "module-ol_format_IIIFInfo-IIIFInfo.html",
    name: "ol​/format​/IIIFInfo",
    children: [],
  },
  {
    path: "module-ol_format_IIIFInfo.html",
    name: "ol​/format​/IIIFInfo",
    children: [],
  },
  {
    path: "module-ol_format_JSONFeature-JSONFeature.html",
    name: "ol​/format​/JSONFeature",
    children: [],
  },
  {
    path: "module-ol_format_KML-KML.html",
    name: "ol​/format​/KML",
    children: [],
  },
  { path: "module-ol_format_KML.html", name: "ol​/format​/KML", children: [] },
  {
    path: "module-ol_format_MVT-MVT.html",
    name: "ol​/format​/MVT",
    children: [],
  },
  {
    path: "module-ol_format_OSMXML-OSMXML.html",
    name: "ol​/format​/OSMXML",
    children: [],
  },
  {
    path: "module-ol_format_Polyline-Polyline.html",
    name: "ol​/format​/Polyline",
    children: [],
  },
  {
    path: "module-ol_format_Polyline.html",
    name: "ol​/format​/Polyline",
    children: [],
  },
  {
    path: "module-ol_format_TextFeature-TextFeature.html",
    name: "ol​/format​/TextFeature",
    children: [],
  },
  {
    path: "module-ol_format_TopoJSON-TopoJSON.html",
    name: "ol​/format​/TopoJSON",
    children: [],
  },
  {
    path: "module-ol_format_TopoJSON.html",
    name: "ol​/format​/TopoJSON",
    children: [],
  },
  {
    path: "module-ol_format_WFS-WFS.html",
    name: "ol​/format​/WFS",
    children: [],
  },
  { path: "module-ol_format_WFS.html", name: "ol​/format​/WFS", children: [] },
  {
    path: "module-ol_format_WKT-WKT.html",
    name: "ol​/format​/WKT",
    children: [],
  },
  { path: "module-ol_format_WKT.html", name: "ol​/format​/WKT", children: [] },
  {
    path: "module-ol_format_WMSCapabilities-WMSCapabilities.html",
    name: "ol​/format​/WMSCapabilities",
    children: [],
  },
  {
    path: "module-ol_format_WMSGetFeatureInfo-WMSGetFeatureInfo.html",
    name: "ol​/format​/WMSGetFeatureInfo",
    children: [],
  },
  {
    path: "module-ol_format_WMTSCapabilities-WMTSCapabilities.html",
    name: "ol​/format​/WMTSCapabilities",
    children: [],
  },
  {
    path: "module-ol_format_XML-XML.html",
    name: "ol​/format​/XML",
    children: [],
  },
  {
    path: "module-ol_format_XMLFeature-XMLFeature.html",
    name: "ol​/format​/XMLFeature",
    children: [],
  },
  {
    path: "module-ol_Geolocation-Geolocation.html",
    name: "ol​/Geolocation",
    children: [],
  },
  {
    path: "module-ol_geom_Circle-Circle.html",
    name: "ol​/geom​/Circle",
    children: [],
  },
  {
    path: "module-ol_geom_Geometry-Geometry.html",
    name: "ol​/geom​/Geometry",
    children: [],
  },
  {
    path: "module-ol_geom_GeometryCollection-GeometryCollection.html",
    name: "ol​/geom​/GeometryCollection",
    children: [],
  },
  {
    path: "module-ol_geom_GeometryLayout.html",
    name: "ol​/geom​/GeometryLayout",
    children: [],
  },
  {
    path: "module-ol_geom_GeometryType.html",
    name: "ol​/geom​/GeometryType",
    children: [],
  },
  {
    path: "module-ol_geom_LinearRing-LinearRing.html",
    name: "ol​/geom​/LinearRing",
    children: [],
  },
  {
    path: "module-ol_geom_LineString-LineString.html",
    name: "ol​/geom​/LineString",
    children: [],
  },
  {
    path: "module-ol_geom_MultiLineString-MultiLineString.html",
    name: "ol​/geom​/MultiLineString",
    children: [],
  },
  {
    path: "module-ol_geom_MultiPoint-MultiPoint.html",
    name: "ol​/geom​/MultiPoint",
    children: [],
  },
  {
    path: "module-ol_geom_MultiPolygon-MultiPolygon.html",
    name: "ol​/geom​/MultiPolygon",
    children: [],
  },
  {
    path: "module-ol_geom_Point-Point.html",
    name: "ol​/geom​/Point",
    children: [],
  },
  {
    path: "module-ol_geom_Polygon-Polygon.html",
    name: "ol​/geom​/Polygon",
    children: [],
  },
  {
    path: "module-ol_geom_Polygon.html",
    name: "ol​/geom​/Polygon",
    children: [],
  },
  {
    path: "module-ol_geom_SimpleGeometry-SimpleGeometry.html",
    name: "ol​/geom​/SimpleGeometry",
    children: [],
  },
  { path: "module-ol_has.html", name: "ol​/has", children: [] },
  {
    path: "module-ol_Image-ImageWrapper.html",
    name: "ol​/Image",
    children: [],
  },
  {
    path: "module-ol_ImageTile-ImageTile.html",
    name: "ol​/ImageTile",
    children: [],
  },
  { path: "module-ol_interaction.html", name: "ol​/interaction", children: [] },
  {
    path: "module-ol_interaction_DoubleClickZoom-DoubleClickZoom.html",
    name: "ol​/interaction​/DoubleClickZoom",
    children: [],
  },
  {
    path: "module-ol_interaction_DragAndDrop-DragAndDrop.html",
    name: "ol​/interaction​/DragAndDrop",
    children: [],
  },
  {
    path: "module-ol_interaction_DragAndDrop-DragAndDropEvent.html",
    name: "ol​/interaction​/DragAndDrop​~DragAndDropEvent",
    children: [],
  },
  {
    path: "module-ol_interaction_DragBox-DragBox.html",
    name: "ol​/interaction​/DragBox",
    children: [],
  },
  {
    path: "module-ol_interaction_DragBox-DragBoxEvent.html",
    name: "ol​/interaction​/DragBox​~DragBoxEvent",
    children: [],
  },
  {
    path: "module-ol_interaction_DragPan-DragPan.html",
    name: "ol​/interaction​/DragPan",
    children: [],
  },
  {
    path: "module-ol_interaction_DragRotate-DragRotate.html",
    name: "ol​/interaction​/DragRotate",
    children: [],
  },
  {
    path: "module-ol_interaction_DragRotateAndZoom-DragRotateAndZoom.html",
    name: "ol​/interaction​/DragRotateAndZoom",
    children: [],
  },
  {
    path: "module-ol_interaction_DragZoom-DragZoom.html",
    name: "ol​/interaction​/DragZoom",
    children: [],
  },
  {
    path: "module-ol_interaction_Draw-Draw.html",
    name: "ol​/interaction​/Draw",
    children: [],
  },
  {
    path: "module-ol_interaction_Draw.html",
    name: "ol​/interaction​/Draw",
    children: [],
  },
  {
    path: "module-ol_interaction_Draw-DrawEvent.html",
    name: "ol​/interaction​/Draw​~DrawEvent",
    children: [],
  },
  {
    path: "module-ol_interaction_Extent-Extent.html",
    name: "ol​/interaction​/Extent",
    children: [],
  },
  {
    path: "module-ol_interaction_Extent-ExtentEvent.html",
    name: "ol​/interaction​/Extent​~ExtentEvent",
    children: [],
  },
  {
    path: "module-ol_interaction_Interaction-Interaction.html",
    name: "ol​/interaction​/Interaction",
    children: [],
  },
  {
    path: "module-ol_interaction_KeyboardPan-KeyboardPan.html",
    name: "ol​/interaction​/KeyboardPan",
    children: [],
  },
  {
    path: "module-ol_interaction_KeyboardZoom-KeyboardZoom.html",
    name: "ol​/interaction​/KeyboardZoom",
    children: [],
  },
  {
    path: "module-ol_interaction_Modify-Modify.html",
    name: "ol​/interaction​/Modify",
    children: [],
  },
  {
    path: "module-ol_interaction_Modify.ModifyEvent.html",
    name: "ol​/interaction​/Modify​.ModifyEvent",
    children: [],
  },
  {
    path: "module-ol_interaction_MouseWheelZoom-MouseWheelZoom.html",
    name: "ol​/interaction​/MouseWheelZoom",
    children: [],
  },
  {
    path: "module-ol_interaction_MouseWheelZoom.html",
    name: "ol​/interaction​/MouseWheelZoom",
    children: [],
  },
  {
    path: "module-ol_interaction_PinchRotate-PinchRotate.html",
    name: "ol​/interaction​/PinchRotate",
    children: [],
  },
  {
    path: "module-ol_interaction_PinchZoom-PinchZoom.html",
    name: "ol​/interaction​/PinchZoom",
    children: [],
  },
  {
    path: "module-ol_interaction_Pointer-PointerInteraction.html",
    name: "ol​/interaction​/Pointer",
    children: [],
  },
  {
    path: "module-ol_interaction_Select-Select.html",
    name: "ol​/interaction​/Select",
    children: [],
  },
  {
    path: "module-ol_interaction_Select-SelectEvent.html",
    name: "ol​/interaction​/Select​~SelectEvent",
    children: [],
  },
  {
    path: "module-ol_interaction_Snap-Snap.html",
    name: "ol​/interaction​/Snap",
    children: [],
  },
  {
    path: "module-ol_interaction_Snap.html",
    name: "ol​/interaction​/Snap",
    children: [],
  },
  {
    path: "module-ol_interaction_Translate-Translate.html",
    name: "ol​/interaction​/Translate",
    children: [],
  },
  {
    path: "module-ol_interaction_Translate.TranslateEvent.html",
    name: "ol​/interaction​/Translate​.TranslateEvent",
    children: [],
  },
  { path: "module-ol_Kinetic-Kinetic.html", name: "ol​/Kinetic", children: [] },
  {
    path: "module-ol_layer_Base-BaseLayer.html",
    name: "ol​/layer​/Base",
    children: [],
  },
  {
    path: "module-ol_layer_BaseImage-BaseImageLayer.html",
    name: "ol​/layer​/BaseImage",
    children: [],
  },
  {
    path: "module-ol_layer_BaseTile-BaseTileLayer.html",
    name: "ol​/layer​/BaseTile",
    children: [],
  },
  {
    path: "module-ol_layer_BaseVector-BaseVectorLayer.html",
    name: "ol​/layer​/BaseVector",
    children: [],
  },
  {
    path: "module-ol_layer_Graticule-Graticule.html",
    name: "ol​/layer​/Graticule",
    children: [],
  },
  {
    path: "module-ol_layer_Graticule.html",
    name: "ol​/layer​/Graticule",
    children: [],
  },
  {
    path: "module-ol_layer_Group-LayerGroup.html",
    name: "ol​/layer​/Group",
    children: [],
  },
  {
    path: "module-ol_layer_Heatmap-Heatmap.html",
    name: "ol​/layer​/Heatmap",
    children: [],
  },
  {
    path: "module-ol_layer_Image-ImageLayer.html",
    name: "ol​/layer​/Image",
    children: [],
  },
  {
    path: "module-ol_layer_Layer-Layer.html",
    name: "ol​/layer​/Layer",
    children: [],
  },
  {
    path: "module-ol_layer_Layer.html",
    name: "ol​/layer​/Layer",
    children: [],
  },
  {
    path: "module-ol_layer_MapboxVector-MapboxVectorLayer.html",
    name: "ol​/layer​/MapboxVector",
    children: [],
  },
  {
    path: "module-ol_layer_MapboxVector.html",
    name: "ol​/layer​/MapboxVector",
    children: [],
  },
  {
    path: "module-ol_layer_Tile-TileLayer.html",
    name: "ol​/layer​/Tile",
    children: [],
  },
  {
    path: "module-ol_layer_Vector-VectorLayer.html",
    name: "ol​/layer​/Vector",
    children: [],
  },
  {
    path: "module-ol_layer_VectorImage-VectorImageLayer.html",
    name: "ol​/layer​/VectorImage",
    children: [],
  },
  {
    path: "module-ol_layer_VectorTile-VectorTileLayer.html",
    name: "ol​/layer​/VectorTile",
    children: [],
  },
  {
    path: "module-ol_layer_VectorTileRenderType.html",
    name: "ol​/layer​/VectorTileRenderType",
    children: [],
  },
  {
    path: "module-ol_loadingstrategy.html",
    name: "ol​/loadingstrategy",
    children: [],
  },
  { path: "module-ol_Map-Map.html", name: "ol​/Map", children: [] },
  {
    path: "module-ol_MapBrowserEvent-MapBrowserEvent.html",
    name: "ol​/MapBrowserEvent",
    children: [],
  },
  {
    path: "module-ol_MapEvent-MapEvent.html",
    name: "ol​/MapEvent",
    children: [],
  },
  {
    path: "module-ol_Object-BaseObject.html",
    name: "ol​/Object",
    children: [],
  },
  {
    path: "module-ol_Object.ObjectEvent.html",
    name: "ol​/Object​.ObjectEvent",
    children: [],
  },
  {
    path: "module-ol_Object.ObjectEvent.html#oldValue",
    name: "oldValue",
    children: [],
  },
  {
    path: "module-ol_Observable-Observable.html",
    name: "ol​/Observable",
    children: [],
  },
  { path: "module-ol_Observable.html", name: "ol​/Observable", children: [] },
  { path: "module-ol_Overlay-Overlay.html", name: "ol​/Overlay", children: [] },
  { path: "module-ol_Overlay.html", name: "ol​/Overlay", children: [] },
  {
    path: "module-ol_OverlayPositioning.html",
    name: "ol​/OverlayPositioning",
    children: [],
  },
  { path: "module-ol_pixel.html", name: "ol​/pixel", children: [] },
  {
    path: "module-ol_PluggableMap-PluggableMap.html",
    name: "ol​/PluggableMap",
    children: [],
  },
  {
    path: "module-ol_PluggableMap.html",
    name: "ol​/PluggableMap",
    children: [],
  },
  { path: "module-ol_proj.html", name: "ol​/proj", children: [] },
  { path: "module-ol_proj_proj4.html", name: "ol​/proj​/proj4", children: [] },
  {
    path: "module-ol_proj_Projection-Projection.html",
    name: "ol​/proj​/Projection",
    children: [],
  },
  { path: "module-ol_proj_Units.html", name: "ol​/proj​/Units", children: [] },
  { path: "module-ol_render.html", name: "ol​/render", children: [] },
  {
    path: "module-ol_render_canvas.html",
    name: "ol​/render​/canvas",
    children: [],
  },
  {
    path: "module-ol_render_canvas_Immediate-CanvasImmediateRenderer.html",
    name: "ol​/render​/canvas​/Immediate",
    children: [],
  },
  {
    path: "module-ol_render_Event-RenderEvent.html",
    name: "ol​/render​/Event",
    children: [],
  },
  {
    path: "module-ol_render_Feature-RenderFeature.html",
    name: "ol​/render​/Feature",
    children: [],
  },
  {
    path: "module-ol_render_VectorContext-VectorContext.html",
    name: "ol​/render​/VectorContext",
    children: [],
  },
  {
    path: "module-ol_renderer_canvas_ImageLayer-CanvasImageLayerRenderer.html",
    name: "ol​/renderer​/canvas​/ImageLayer",
    children: [],
  },
  {
    path: "module-ol_renderer_canvas_TileLayer-CanvasTileLayerRenderer.html",
    name: "ol​/renderer​/canvas​/TileLayer",
    children: [],
  },
  {
    path:
      "module-ol_renderer_canvas_VectorImageLayer-CanvasVectorImageLayerRenderer.html",
    name: "ol​/renderer​/canvas​/VectorImageLayer",
    children: [],
  },
  {
    path:
      "module-ol_renderer_canvas_VectorLayer-CanvasVectorLayerRenderer.html",
    name: "ol​/renderer​/canvas​/VectorLayer",
    children: [],
  },
  {
    path:
      "module-ol_renderer_canvas_VectorTileLayer-CanvasVectorTileLayerRenderer.html",
    name: "ol​/renderer​/canvas​/VectorTileLayer",
    children: [],
  },
  {
    path: "module-ol_renderer_Composite-CompositeMapRenderer.html",
    name: "ol​/renderer​/Composite",
    children: [],
  },
  {
    path: "module-ol_renderer_webgl_Layer-WebGLLayerRenderer.html",
    name: "ol​/renderer​/webgl​/Layer",
    children: [],
  },
  {
    path: "module-ol_renderer_webgl_Layer.html",
    name: "ol​/renderer​/webgl​/Layer",
    children: [],
  },
  {
    path: "module-ol_renderer_webgl_PointsLayer-WebGLPointsLayerRenderer.html",
    name: "ol​/renderer​/webgl​/PointsLayer",
    children: [],
  },
  {
    path: "module-ol_renderer_webgl_PointsLayer.html",
    name: "ol​/renderer​/webgl​/PointsLayer",
    children: [],
  },
  { path: "module-ol_size.html", name: "ol​/size", children: [] },
  {
    path: "module-ol_source_BingMaps-BingMaps.html",
    name: "ol​/source​/BingMaps",
    children: [],
  },
  {
    path: "module-ol_source_BingMaps.html",
    name: "ol​/source​/BingMaps",
    children: [],
  },
  {
    path: "module-ol_source_CartoDB-CartoDB.html",
    name: "ol​/source​/CartoDB",
    children: [],
  },
  {
    path: "module-ol_source_CartoDB.html",
    name: "ol​/source​/CartoDB",
    children: [],
  },
  {
    path: "module-ol_source_Cluster-Cluster.html",
    name: "ol​/source​/Cluster",
    children: [],
  },
  {
    path: "module-ol_source_IIIF-IIIF.html",
    name: "ol​/source​/IIIF",
    children: [],
  },
  {
    path: "module-ol_source_Image-ImageSource.html",
    name: "ol​/source​/Image",
    children: [],
  },
  {
    path: "module-ol_source_Image.html",
    name: "ol​/source​/Image",
    children: [],
  },
  {
    path: "module-ol_source_Image.ImageSourceEvent.html",
    name: "ol​/source​/Image​.ImageSourceEvent",
    children: [],
  },
  {
    path: "module-ol_source_ImageArcGISRest-ImageArcGISRest.html",
    name: "ol​/source​/ImageArcGISRest",
    children: [],
  },
  {
    path: "module-ol_source_ImageCanvas-ImageCanvasSource.html",
    name: "ol​/source​/ImageCanvas",
    children: [],
  },
  {
    path: "module-ol_source_ImageCanvas.html",
    name: "ol​/source​/ImageCanvas",
    children: [],
  },
  {
    path: "module-ol_source_ImageMapGuide-ImageMapGuide.html",
    name: "ol​/source​/ImageMapGuide",
    children: [],
  },
  {
    path: "module-ol_source_ImageStatic-Static.html",
    name: "ol​/source​/ImageStatic",
    children: [],
  },
  {
    path: "module-ol_source_ImageWMS-ImageWMS.html",
    name: "ol​/source​/ImageWMS",
    children: [],
  },
  {
    path: "module-ol_source_OSM-OSM.html",
    name: "ol​/source​/OSM",
    children: [],
  },
  { path: "module-ol_source_OSM.html", name: "ol​/source​/OSM", children: [] },
  {
    path: "module-ol_source_Raster-RasterSource.html",
    name: "ol​/source​/Raster",
    children: [],
  },
  {
    path: "module-ol_source_Raster.html",
    name: "ol​/source​/Raster",
    children: [],
  },
  {
    path: "module-ol_source_Raster.RasterSourceEvent.html",
    name: "ol​/source​/Raster​.RasterSourceEvent",
    children: [],
  },
  {
    path: "module-ol_source_Source-Source.html",
    name: "ol​/source​/Source",
    children: [],
  },
  {
    path: "module-ol_source_Source.html",
    name: "ol​/source​/Source",
    children: [],
  },
  {
    path: "module-ol_source_Stamen-Stamen.html",
    name: "ol​/source​/Stamen",
    children: [],
  },
  {
    path: "module-ol_source_State.html",
    name: "ol​/source​/State",
    children: [],
  },
  {
    path: "module-ol_source_Tile-TileSource.html",
    name: "ol​/source​/Tile",
    children: [],
  },
  {
    path: "module-ol_source_Tile.TileSourceEvent.html",
    name: "ol​/source​/Tile​.TileSourceEvent",
    children: [],
  },
  {
    path: "module-ol_source_TileArcGISRest-TileArcGISRest.html",
    name: "ol​/source​/TileArcGISRest",
    children: [],
  },
  {
    path: "module-ol_source_TileDebug-TileDebug.html",
    name: "ol​/source​/TileDebug",
    children: [],
  },
  {
    path: "module-ol_source_TileImage-TileImage.html",
    name: "ol​/source​/TileImage",
    children: [],
  },
  {
    path: "module-ol_source_TileJSON-TileJSON.html",
    name: "ol​/source​/TileJSON",
    children: [],
  },
  {
    path: "module-ol_source_TileJSON.html",
    name: "ol​/source​/TileJSON",
    children: [],
  },
  {
    path: "module-ol_source_TileWMS-TileWMS.html",
    name: "ol​/source​/TileWMS",
    children: [],
  },
  {
    path: "module-ol_source_UrlTile-UrlTile.html",
    name: "ol​/source​/UrlTile",
    children: [],
  },
  {
    path: "module-ol_source_UTFGrid-UTFGrid.html",
    name: "ol​/source​/UTFGrid",
    children: [],
  },
  {
    path: "module-ol_source_UTFGrid.html",
    name: "ol​/source​/UTFGrid",
    children: [],
  },
  {
    path: "module-ol_source_Vector-VectorSource.html",
    name: "ol​/source​/Vector",
    children: [],
  },
  {
    path: "module-ol_source_Vector.VectorSourceEvent.html",
    name: "ol​/source​/Vector​.VectorSourceEvent",
    children: [],
  },
  {
    path: "module-ol_source_VectorTile-VectorTile.html",
    name: "ol​/source​/VectorTile",
    children: [],
  },
  {
    path: "module-ol_source_WMSServerType.html",
    name: "ol​/source​/WMSServerType",
    children: [],
  },
  {
    path: "module-ol_source_WMTS-WMTS.html",
    name: "ol​/source​/WMTS",
    children: [],
  },
  {
    path: "module-ol_source_WMTS.html",
    name: "ol​/source​/WMTS",
    children: [],
  },
  {
    path: "module-ol_source_WMTSRequestEncoding.html",
    name: "ol​/source​/WMTSRequestEncoding",
    children: [],
  },
  {
    path: "module-ol_source_XYZ-XYZ.html",
    name: "ol​/source​/XYZ",
    children: [],
  },
  {
    path: "module-ol_source_Zoomify-Zoomify.html",
    name: "ol​/source​/Zoomify",
    children: [],
  },
  { path: "module-ol_sphere.html", name: "ol​/sphere", children: [] },
  {
    path: "module-ol_structs_LRUCache-LRUCache.html",
    name: "ol​/structs​/LRUCache",
    children: [],
  },
  {
    path: "module-ol_style_Circle-CircleStyle.html",
    name: "ol​/style​/Circle",
    children: [],
  },
  {
    path: "module-ol_style_Fill-Fill.html",
    name: "ol​/style​/Fill",
    children: [],
  },
  {
    path: "module-ol_style_Icon-Icon.html",
    name: "ol​/style​/Icon",
    children: [],
  },
  {
    path: "module-ol_style_IconAnchorUnits.html",
    name: "ol​/style​/IconAnchorUnits",
    children: [],
  },
  {
    path: "module-ol_style_IconImageCache-IconImageCache.html",
    name: "ol​/style​/IconImageCache",
    children: [],
  },
  {
    path: "module-ol_style_IconImageCache.html",
    name: "ol​/style​/IconImageCache",
    children: [],
  },
  {
    path: "module-ol_style_IconOrigin.html",
    name: "ol​/style​/IconOrigin",
    children: [],
  },
  {
    path: "module-ol_style_Image-ImageStyle.html",
    name: "ol​/style​/Image",
    children: [],
  },
  {
    path: "module-ol_style_RegularShape-RegularShape.html",
    name: "ol​/style​/RegularShape",
    children: [],
  },
  {
    path: "module-ol_style_RegularShape.html",
    name: "ol​/style​/RegularShape",
    children: [],
  },
  {
    path: "module-ol_style_Stroke-Stroke.html",
    name: "ol​/style​/Stroke",
    children: [],
  },
  {
    path: "module-ol_style_Style-Style.html",
    name: "ol​/style​/Style",
    children: [],
  },
  {
    path: "module-ol_style_Style.html",
    name: "ol​/style​/Style",
    children: [],
  },
  {
    path: "module-ol_style_Text-Text.html",
    name: "ol​/style​/Text",
    children: [],
  },
  {
    path: "module-ol_style_TextPlacement.html",
    name: "ol​/style​/TextPlacement",
    children: [],
  },
  { path: "module-ol_Tile-Tile.html", name: "ol​/Tile", children: [] },
  { path: "module-ol_Tile.html", name: "ol​/Tile", children: [] },
  { path: "module-ol_tilecoord.html", name: "ol​/tilecoord", children: [] },
  { path: "module-ol_tilegrid.html", name: "ol​/tilegrid", children: [] },
  {
    path: "module-ol_tilegrid_TileGrid-TileGrid.html",
    name: "ol​/tilegrid​/TileGrid",
    children: [],
  },
  {
    path: "module-ol_tilegrid_WMTS-WMTSTileGrid.html",
    name: "ol​/tilegrid​/WMTS",
    children: [],
  },
  {
    path: "module-ol_tilegrid_WMTS.html",
    name: "ol​/tilegrid​/WMTS",
    children: [],
  },
  { path: "module-ol_TileState.html", name: "ol​/TileState", children: [] },
  { path: "module-ol_transform.html", name: "ol​/transform", children: [] },
  { path: "module-ol_util.html", name: "ol​/util", children: [] },
  {
    path: "module-ol_VectorTile-VectorTile.html",
    name: "ol​/VectorTile",
    children: [],
  },
  { path: "module-ol_View-View.html", name: "ol​/View", children: [] },
  { path: "module-ol_View.html", name: "ol​/View", children: [] },
  { path: "module-ol_webgl.html", name: "ol​/webgl", children: [] },
  {
    path: "module-ol_webgl_Buffer-WebGLArrayBuffer.html",
    name: "ol​/webgl​/Buffer",
    children: [],
  },
  {
    path: "module-ol_webgl_Buffer.html",
    name: "ol​/webgl​/Buffer",
    children: [],
  },
  {
    path: "module-ol_webgl_Helper-WebGLHelper.html",
    name: "ol​/webgl​/Helper",
    children: [],
  },
  {
    path: "module-ol_webgl_Helper.html",
    name: "ol​/webgl​/Helper",
    children: [],
  },
  {
    path: "module-ol_webgl_PostProcessingPass-WebGLPostProcessingPass.html",
    name: "ol​/webgl​/PostProcessingPass",
    children: [],
  },
  {
    path: "module-ol_webgl_RenderTarget-WebGLRenderTarget.html",
    name: "ol​/webgl​/RenderTarget",
    children: [],
  },
  { path: "module-ol_xml.html", name: "ol​/xml", children: [] },
];
